/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileImport } from './routes/profile'
import { Route as EchartImport } from './routes/echart'
import { Route as IndexImport } from './routes/index'
import { Route as PokemonsIndexImport } from './routes/pokemons/index'
import { Route as PokemonsIdImport } from './routes/pokemons/$id'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthSigninImport } from './routes/auth/signin'
import { Route as PostsIdEditImport } from './routes/posts/$id/edit'

// Create/Update Routes

const ProfileRoute = ProfileImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const EchartRoute = EchartImport.update({
  path: '/echart',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PokemonsIndexRoute = PokemonsIndexImport.update({
  path: '/pokemons/',
  getParentRoute: () => rootRoute,
} as any)

const PokemonsIdRoute = PokemonsIdImport.update({
  path: '/pokemons/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthSigninRoute = AuthSigninImport.update({
  path: '/auth/signin',
  getParentRoute: () => rootRoute,
} as any)

const PostsIdEditRoute = PostsIdEditImport.update({
  path: '/posts/$id/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/echart': {
      preLoaderRoute: typeof EchartImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/auth/signin': {
      preLoaderRoute: typeof AuthSigninImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/pokemons/$id': {
      preLoaderRoute: typeof PokemonsIdImport
      parentRoute: typeof rootRoute
    }
    '/pokemons/': {
      preLoaderRoute: typeof PokemonsIndexImport
      parentRoute: typeof rootRoute
    }
    '/posts/$id/edit': {
      preLoaderRoute: typeof PostsIdEditImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  EchartRoute,
  ProfileRoute,
  AuthSigninRoute,
  AuthSignupRoute,
  PokemonsIdRoute,
  PokemonsIndexRoute,
  PostsIdEditRoute,
])

/* prettier-ignore-end */
