@baseUrl = https://localhost:8080

### get all users
{{baseUrl}}/api/users
Accept: application/json

### get user by id
{{baseUrl}}/api/users/3

### get user by name
{{baseUrl}}/api/users/name/nadjib

### Update user (even the password)
PUT https://localhost:8080/api/users
Content-Type: application/json

{
    "id": 2,
    "name" : "nad",
    "password": "123456",
    "is_active": true
}

### DELETE /users/:id
DELETE https://localhost:8080/api/users/10
