@baseUrl = https://localhost:8080


### Check Username Existance
{{baseUrl}}/api/auth/check-name/nad

### Sign-up
POST {{baseUrl}}/api/auth/signup
Content-Type: application/json

{
    "name": "n4djib4",
    "password": "123456"
}

### Sign-in (login)
POST {{baseUrl}}/api/auth/signin
Content-Type: application/json

{
    "name": "n4djib3",
    "password": "123456"
}

### Activate User
PUT {{baseUrl}}/api/auth/active-state
Content-Type: application/json

{
    "id": 2,
    "is_active": true
}

### Who Am I
GET {{baseUrl}}/api/auth/whoami

### get all users (testing authenticated)
{{baseUrl}}/api/users

### Sign-out (logout)
{{baseUrl}}/api/auth/signout





### get all users
{{baseUrl}}/api/users
Accept: application/json

### get user by id
{{baseUrl}}/api/users/3

### get user by name
{{baseUrl}}/api/users/name/nadjib

### Update user (even the password)
PUT https://localhost:8080/api/users
Content-Type: application/json

{
    "id": 2,
    "name" : "nad",
    "password": "123456",
    "is_active": true
}

### DELETE /users/:id
DELETE https://localhost:8080/api/users/10
