// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"time"
)

type Pokemon struct {
	ID    int64  `db:"id" json:"id"`
	Name  string `db:"name" json:"name"`
	Image string `db:"image" json:"image"`
}

type User struct {
	ID        int64      `db:"id" json:"id"`
	Name      string     `db:"name" json:"name" validate:"required"`
	Password  string     `db:"password" json:"password" validate:"required"`
	IsActive  *bool      `db:"is_active" json:"is_active"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}
