// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"time"
)

type Permission struct {
	ID          int64   `db:"id" json:"id"`
	Permission  string  `db:"permission" json:"permission"`
	Description *string `db:"description" json:"description"`
	Rule        *string `db:"rule" json:"rule"`
}

type PermissionParent struct {
	PermissionID int64 `db:"permission_id" json:"permission_id"`
	ParentID     int64 `db:"parent_id" json:"parent_id"`
}

type Pokemon struct {
	ID    int64  `db:"id" json:"id"`
	Name  string `db:"name" json:"name"`
	Image string `db:"image" json:"image"`
}

type Role struct {
	ID          int64   `db:"id" json:"id"`
	Role        string  `db:"role" json:"role"`
	Description *string `db:"description" json:"description"`
}

type RoleParent struct {
	RoleID   int64 `db:"role_id" json:"role_id"`
	ParentID int64 `db:"parent_id" json:"parent_id"`
}

type RolePermission struct {
	RoleID       int64 `db:"role_id" json:"role_id"`
	PermissionID int64 `db:"permission_id" json:"permission_id"`
}

type User struct {
	ID        int64      `db:"id" json:"id"`
	Name      string     `db:"name" json:"name" validate:"required"`
	Password  string     `db:"password" json:"password" validate:"required"`
	IsActive  *bool      `db:"is_active" json:"is_active"`
	Session   *string    `db:"session" json:"session"`
	LoggedAt  *time.Time `db:"logged_at" json:"logged_at"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}

type UserRole struct {
	UserID int64 `db:"user_id" json:"user_id"`
	RoleID int64 `db:"role_id" json:"role_id"`
}
